// Datos de la tabla periódica.
// Formato: [número atómico, símbolo, nombre, masa atómica, categoría]
// En los elementos sintéticos la masa corresponde al isótopo más estable.
const ELEMENTOS_DATOS = [
  [1, 'H', 'Hidrógeno', 1.008, 'nometal'],
  [2, 'He', 'Helio', 4.0026, 'noble'],
  [3, 'Li', 'Litio', 6.94, 'alcalino'],
  [4, 'Be', 'Berilio', 9.0122, 'alcalinoterreo'],
  [5, 'B', 'Boro', 10.81, 'metaloide'],
  [6, 'C', 'Carbono', 12.011, 'nometal'],
  [7, 'N', 'Nitrógeno', 14.007, 'nometal'],
  [8, 'O', 'Oxígeno', 15.999, 'nometal'],
  [9, 'F', 'Flúor', 18.998, 'halogeno'],
  [10, 'Ne', 'Neón', 20.18, 'noble'],
  [11, 'Na', 'Sodio', 22.99, 'alcalino'],
  [12, 'Mg', 'Magnesio', 24.305, 'alcalinoterreo'],
  [13, 'Al', 'Aluminio', 26.982, 'postransicion'],
  [14, 'Si', 'Silicio', 28.085, 'metaloide'],
  [15, 'P', 'Fósforo', 30.974, 'nometal'],
  [16, 'S', 'Azufre', 32.06, 'nometal'],
  [17, 'Cl', 'Cloro', 35.45, 'halogeno'],
  [18, 'Ar', 'Argón', 39.948, 'noble'],
  [19, 'K', 'Potasio', 39.098, 'alcalino'],
  [20, 'Ca', 'Calcio', 40.078, 'alcalinoterreo'],
  [21, 'Sc', 'Escandio', 44.956, 'transicion'],
  [22, 'Ti', 'Titanio', 47.867, 'transicion'],
  [23, 'V', 'Vanadio', 50.942, 'transicion'],
  [24, 'Cr', 'Cromo', 51.996, 'transicion'],
  [25, 'Mn', 'Manganeso', 54.938, 'transicion'],
  [26, 'Fe', 'Hierro', 55.845, 'transicion'],
  [27, 'Co', 'Cobalto', 58.933, 'transicion'],
  [28, 'Ni', 'Níquel', 58.693, 'transicion'],
  [29, 'Cu', 'Cobre', 63.546, 'transicion'],
  [30, 'Zn', 'Zinc', 65.38, 'transicion'],
  [31, 'Ga', 'Galio', 69.723, 'postransicion'],
  [32, 'Ge', 'Germanio', 72.63, 'metaloide'],
  [33, 'As', 'Arsénico', 74.922, 'metaloide'],
  [34, 'Se', 'Selenio', 78.971, 'nometal'],
  [35, 'Br', 'Bromo', 79.904, 'halogeno'],
  [36, 'Kr', 'Kriptón', 83.798, 'noble'],
  [37, 'Rb', 'Rubidio', 85.468, 'alcalino'],
  [38, 'Sr', 'Estroncio', 87.62, 'alcalinoterreo'],
  [39, 'Y', 'Itrio', 88.906, 'transicion'],
  [40, 'Zr', 'Circonio', 91.224, 'transicion'],
  [41, 'Nb', 'Niobio', 92.906, 'transicion'],
  [42, 'Mo', 'Molibdeno', 95.95, 'transicion'],
  [43, 'Tc', 'Tecnecio', 98, 'transicion'],
  [44, 'Ru', 'Rutenio', 101.07, 'transicion'],
  [45, 'Rh', 'Rodio', 102.91, 'transicion'],
  [46, 'Pd', 'Paladio', 106.42, 'transicion'],
  [47, 'Ag', 'Plata', 107.87, 'transicion'],
  [48, 'Cd', 'Cadmio', 112.41, 'transicion'],
  [49, 'In', 'Indio', 114.82, 'postransicion'],
  [50, 'Sn', 'Estaño', 118.71, 'postransicion'],
  [51, 'Sb', 'Antimonio', 121.76, 'metaloide'],
  [52, 'Te', 'Telurio', 127.6, 'metaloide'],
  [53, 'I', 'Yodo', 126.9, 'halogeno'],
  [54, 'Xe', 'Xenón', 131.29, 'noble'],
  [55, 'Cs', 'Cesio', 132.91, 'alcalino'],
  [56, 'Ba', 'Bario', 137.33, 'alcalinoterreo'],
  [57, 'La', 'Lantano', 138.91, 'lantanido'],
  [58, 'Ce', 'Cerio', 140.12, 'lantanido'],
  [59, 'Pr', 'Praseodimio', 140.91, 'lantanido'],
  [60, 'Nd', 'Neodimio', 144.24, 'lantanido'],
  [61, 'Pm', 'Prometio', 145, 'lantanido'],
  [62, 'Sm', 'Samario', 150.36, 'lantanido'],
  [63, 'Eu', 'Europio', 151.96, 'lantanido'],
  [64, 'Gd', 'Gadolinio', 157.25, 'lantanido'],
  [65, 'Tb', 'Terbio', 158.93, 'lantanido'],
  [66, 'Dy', 'Disprosio', 162.5, 'lantanido'],
  [67, 'Ho', 'Holmio', 164.93, 'lantanido'],
  [68, 'Er', 'Erbio', 167.26, 'lantanido'],
  [69, 'Tm', 'Tulio', 168.93, 'lantanido'],
  [70, 'Yb', 'Iterbio', 173.05, 'lantanido'],
  [71, 'Lu', 'Lutecio', 174.97, 'lantanido'],
  [72, 'Hf', 'Hafnio', 178.49, 'transicion'],
  [73, 'Ta', 'Tantalio', 180.95, 'transicion'],
  [74, 'W', 'Wolframio', 183.84, 'transicion'],
  [75, 'Re', 'Renio', 186.21, 'transicion'],
  [76, 'Os', 'Osmio', 190.23, 'transicion'],
  [77, 'Ir', 'Iridio', 192.22, 'transicion'],
  [78, 'Pt', 'Platino', 195.08, 'transicion'],
  [79, 'Au', 'Oro', 196.97, 'transicion'],
  [80, 'Hg', 'Mercurio', 200.59, 'transicion'],
  [81, 'Tl', 'Talio', 204.38, 'postransicion'],
  [82, 'Pb', 'Plomo', 207.2, 'postransicion'],
  [83, 'Bi', 'Bismuto', 208.98, 'postransicion'],
  [84, 'Po', 'Polonio', 209, 'postransicion'],
  [85, 'At', 'Astato', 210, 'halogeno'],
  [86, 'Rn', 'Radón', 222, 'noble'],
  [87, 'Fr', 'Francio', 223, 'alcalino'],
  [88, 'Ra', 'Radio', 226, 'alcalinoterreo'],
  [89, 'Ac', 'Actinio', 227, 'actinido'],
  [90, 'Th', 'Torio', 232.04, 'actinido'],
  [91, 'Pa', 'Protactinio', 231.04, 'actinido'],
  [92, 'U', 'Uranio', 238.03, 'actinido'],
  [93, 'Np', 'Neptunio', 237, 'actinido'],
  [94, 'Pu', 'Plutonio', 244, 'actinido'],
  [95, 'Am', 'Americio', 243, 'actinido'],
  [96, 'Cm', 'Curio', 247, 'actinido'],
  [97, 'Bk', 'Berkelio', 247, 'actinido'],
  [98, 'Cf', 'Californio', 251, 'actinido'],
  [99, 'Es', 'Einstenio', 252, 'actinido'],
  [100, 'Fm', 'Fermio', 257, 'actinido'],
  [101, 'Md', 'Mendelevio', 258, 'actinido'],
  [102, 'No', 'Nobelio', 259, 'actinido'],
  [103, 'Lr', 'Lawrencio', 266, 'actinido'],
  [104, 'Rf', 'Rutherfordio', 267, 'transicion'],
  [105, 'Db', 'Dubnio', 268, 'transicion'],
  [106, 'Sg', 'Seaborgio', 269, 'transicion'],
  [107, 'Bh', 'Bohrio', 270, 'transicion'],
  [108, 'Hs', 'Hasio', 277, 'transicion'],
  [109, 'Mt', 'Meitnerio', 278, 'transicion'],
  [110, 'Ds', 'Darmstatio', 281, 'transicion'],
  [111, 'Rg', 'Roentgenio', 282, 'transicion'],
  [112, 'Cn', 'Copernicio', 285, 'transicion'],
  [113, 'Nh', 'Nihonio', 286, 'postransicion'],
  [114, 'Fl', 'Flerovio', 289, 'postransicion'],
  [115, 'Mc', 'Moscovio', 290, 'postransicion'],
  [116, 'Lv', 'Livermorio', 293, 'postransicion'],
  [117, 'Ts', 'Teneso', 294, 'halogeno'],
  [118, 'Og', 'Oganesón', 294, 'noble'],
];

const CATEGORIAS = {
  alcalino:       { nombre: 'Metales alcalinos',       singular: 'metal alcalino',       color: '#ffc9c9', tipo: 'metal' },
  alcalinoterreo: { nombre: 'Metales alcalinotérreos', singular: 'metal alcalinotérreo', color: '#ffd8a8', tipo: 'metal' },
  transicion:     { nombre: 'Metales de transición',   singular: 'metal de transición',  color: '#ffec99', tipo: 'metal' },
  postransicion:  { nombre: 'Otros metales',           singular: 'metal del bloque p',   color: '#d8f5a2', tipo: 'metal' },
  metaloide:      { nombre: 'Metaloides',              singular: 'metaloide',            color: '#b2f2bb', tipo: 'metaloide' },
  nometal:        { nombre: 'No metales',              singular: 'no metal',             color: '#a5d8ff', tipo: 'nometal' },
  halogeno:       { nombre: 'Halógenos',               singular: 'halógeno',             color: '#99e9f2', tipo: 'nometal' },
  noble:          { nombre: 'Gases nobles',            singular: 'gas noble',            color: '#d0bfff', tipo: 'nometal' },
  lantanido:      { nombre: 'Lantánidos',              singular: 'lantánido',            color: '#fcc2d7', tipo: 'metal' },
  actinido:       { nombre: 'Actínidos',               singular: 'actínido',             color: '#eebefa', tipo: 'metal' },
};

// Estado de agregación a 25 °C.
const GASES = [1, 2, 7, 8, 9, 10, 17, 18, 36, 54, 86];
const LIQUIDOS = [35, 80];

const USOS = {
  1: 'Es el elemento más abundante del universo. Las estrellas, como el Sol, lo transforman en helio.',
  2: 'Es más liviano que el aire: se usa para inflar globos y dirigibles.',
  3: 'Se usa en las baterías de celulares y autos eléctricos.',
  6: 'Es la base de todos los seres vivos. El diamante y el grafito del lápiz son carbono puro.',
  7: 'Forma el 78 % del aire que respiramos.',
  8: 'Lo necesitamos para respirar y forma el 21 % del aire.',
  9: 'Se agrega como fluoruro a las pastas dentales para proteger los dientes.',
  10: 'Brilla con luz rojo-anaranjada en los carteles luminosos.',
  11: 'Es tan blando que se corta con un cuchillo y reacciona violentamente con el agua. Forma parte de la sal de mesa.',
  12: 'Arde con una luz blanca muy intensa: se usa en bengalas y fuegos artificiales.',
  13: 'Liviano y resistente: latas, papel de aluminio y aviones.',
  14: 'Es la base de los chips de computadoras y de los paneles solares.',
  15: 'Está en la cabeza de los fósforos, en nuestros huesos y en el ADN.',
  16: 'Es amarillo. Algunos de sus compuestos tienen olor a huevo podrido.',
  17: 'Se usa para potabilizar el agua y desinfectar piscinas.',
  18: 'Gas inerte que se usa dentro de lámparas y en soldadura.',
  19: 'Es esencial para músculos y nervios. La banana es rica en potasio.',
  20: 'Forma huesos, dientes, cáscaras de huevo y el mármol.',
  22: 'Metal liviano y muy resistente: prótesis, implantes dentales y aviones.',
  26: 'Es el metal más usado del mundo (en forma de acero). En la sangre transporta oxígeno.',
  29: 'Es un excelente conductor: se usa en los cables eléctricos.',
  30: 'Recubre al hierro para que no se oxide (hierro galvanizado).',
  47: 'Es el mejor conductor eléctrico de todos los metales. Se usa en joyería.',
  50: 'Se usa en soldaduras y para recubrir latas de conserva (hojalata).',
  53: 'Lo necesita la glándula tiroides; por eso se agrega a la sal de mesa (sal yodada).',
  54: 'Se usa en faros de autos y en motores de naves espaciales.',
  78: 'Se usa en los convertidores catalíticos de los autos para reducir la contaminación.',
  79: 'No se oxida y es muy maleable: joyería y contactos electrónicos.',
  80: 'Es el único metal líquido a temperatura ambiente. Es tóxico.',
  82: 'Es muy denso y se usa como protección contra la radiación. Es tóxico.',
  86: 'Gas radiactivo que puede acumularse en sótanos mal ventilados.',
  92: 'Se usa como combustible en las centrales nucleares.',
};

// Ubicación en la tabla. Filas 9 y 10 = lantánidos y actínidos.
function posicionElemento(z) {
  if (z === 1) return { grupo: 1, periodo: 1, fila: 1, col: 1 };
  if (z === 2) return { grupo: 18, periodo: 1, fila: 1, col: 18 };
  const inicios = [[3, 2], [11, 3], [19, 4], [37, 5], [55, 6], [87, 7]];
  let periodo = 2, inicio = 3;
  for (const [s, p] of inicios) if (z >= s) { periodo = p; inicio = s; }
  const k = z - inicio;
  let grupo;
  if (periodo <= 3) grupo = k < 2 ? k + 1 : k + 11;
  else if (periodo <= 5) grupo = k + 1;
  else if (k < 2) grupo = k + 1;
  else if (k <= 16) return { grupo: null, periodo, fila: periodo === 6 ? 9 : 10, col: k + 1 };
  else grupo = k - 13;
  return { grupo, periodo, fila: periodo, col: grupo };
}

const ELEMENTOS = ELEMENTOS_DATOS.map(([z, simbolo, nombre, masa, categoria]) => ({
  z, simbolo, nombre, masa, categoria,
  ...posicionElemento(z),
  estado: GASES.includes(z) ? 'gas' : LIQUIDOS.includes(z) ? 'liquido' : z >= 100 ? 'desconocido' : 'solido',
  uso: USOS[z] || null,
}));
